/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'static-menu/intro',
    {
      type: 'autogenerated',
      dirName: 'Our Identity', // Generate sidebar slice from docs/Our Identity
    },
    {
      type: 'autogenerated',
      dirName: 'Our People', // Generate sidebar slice from docs/Our People
    },
    {
      type: 'autogenerated',
      dirName: 'Our Practices', // Generate sidebar slice from docs/Our Practices
    },
    {
      type: 'link',
      label: 'Blog',
      href: '/blog',
    },
    'static-menu/contribute',
  ],
};

module.exports = sidebars;
