/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Our Identity',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Our Identity', // Generate sidebar slice from docs/Our Identity
        },
      ]
    },
    {
      type: 'category',
      label: 'Our People',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Our People', // Generate sidebar slice from docs/Our People
        },
      ]
    },
    {
      type: 'category',
      label: 'Our Practices',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Our Practices', // Generate sidebar slice from docs/Our Practices
        },
      ]
    },
    {
      type: 'link',
      label: 'Blog',
      href: '/blog',
    },
    'contribute',
  ],
};

module.exports = sidebars;
