version: "3.7"
services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.3.0
    command:
      - --http-address
      - 0.0.0.0:4180 
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://localhost:3000/ 
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: github
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_CLIENT_ID: <YOUR_CLIENT_ID>
      OAUTH2_PROXY_CLIENT_SECRET: <YOUR_CLIENT_SECRET>
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true 
      OAUTH2_PROXY_EMAIL_DOMAINS: '*' 
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:3000/
      OAUTH2_PROXY_COOKIE_SECRET: <YOUR_COOKIE_SECRET>

    ports:
      - 4180:4180
