name: "Lambda Pull Request"
on:
  pull_request:
    paths:
      - "lambda/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Set up Python 3.10
        uses: actions/setup-python
        with:
          python-version: 3.10

      - name: Install Tox
        run: pip install tox
        working-directory: lambda

      - name: Run unit tests
        run: tox
        working-directory: lambda
