name: "Pull Request"
on:
  pull_request:

    paths-ignore:
      - "**/*.tf"
  workflow_dispatch: {}

jobs:
  pull-request:
    name: "Build Handbook content"
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - uses: actions/checkout@v2

      - name: "Pull PUBLIC handbook content"
        id: public-content
        run: |
          git clone https://github.com/BurendoUK/burendo-handbook-public.git
        working-directory: .
        continue-on-error: false
      
      - name: "Move PUBLIC handbook content"
        id: public-content-copy
        run: |
          mkdir -p burendo-handbook/docs
          mv burendo-handbook-public/docs/* burendo-handbook/docs
        working-directory: .
        continue-on-error: false

      - name: "Build handbook with content"
        id: build-handbook
        run: |
          npm install
          npm run build
        working-directory: ./burendo-handbook
        continue-on-error: false
