name: "Pull Request"
on:
  pull_request:

    paths-ignore:
      - "**/*.tf"
  workflow_dispatch: {}

jobs:
  pull-request:
    name: "Build Handbook content"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: "Install dependencies"
        id: deps
        run: pip install Jinja2 PyYAML boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_GHA_ROLE }}
          role-duration-seconds: 900
          role-session-name: ${{ github.run_id }}-${{ github.run_number }}
          aws-region: eu-west-2

      - name: "Bootstrap"
        id: bootstrap
        run: |
          python bootstrap.py > ${{ github.workspace }}/${{ github.run_id }}-${{ github.run_number }}.log
          sed -i "s/Administrator/ci/" terraform/variables.tf
        working-directory: .
        env:
          TF_WORKSPACE: burendo-prod
          AWS_SECRETS_ROLE: ${{ secrets.AWS_GHA_ROLE }}
          AWS_DEFAULT_REGION: eu-west-2

      - name: "Pull PUBLIC handbook content"
        id: public-content
        run: |
          git clone https://github.com/BurendoUK/burendo-handbook-public.git
        working-directory: .
        continue-on-error: false
      
      - name: "Move PUBLIC handbook content"
        id: public-content-copy
        run: |
          mkdir -p burendo-handbook/docs
          mv burendo-handbook-public/docs/* burendo-handbook/docs
        working-directory: .
        continue-on-error: false
      
      - name: "Move PUBLIC blog content"
        id: public-blog-copy
        run: |
          mkdir -p burendo-handbook/blog
          mv burendo-handbook-public/blog/* burendo-handbook/blog
        working-directory: .
        continue-on-error: false

      - name: "Pull PRIVATE handbook content"
        id: private-content
        run: |
          echo "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/BurendoUK/burendo-handbook-private"
          git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/BurendoUK/burendo-handbook-private
        working-directory: .
        continue-on-error: false
        env:
          GITHUB_USER: ${{ secrets.GH_USER }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: "Move PRIVATE handbook content"
        id: private-content-copy
        run: |
          mkdir -p burendo-handbook/docs/private
          mv burendo-handbook-private/docs/* burendo-handbook/docs/private
        working-directory: .
        continue-on-error: false

      - name: "Rename Public Sidebars Config"
        id: rename-public-config
        run: mv sidebars.public.js sidebars.js
        working-directory: ./burendo-handbook
        continue-on-error: false

      - name: "Build handbook with content"
        id: build-public-handbook
        run: |
          npm install
          npm run build
        working-directory: ./burendo-handbook
        continue-on-error: false

      - name: "Reset Sidebars Config"
        id: reset-config
        run: mv sidebars.js sidebars.public.js
        working-directory: ./burendo-handbook
        continue-on-error: false

      - name: "Rename Private Sidebars Config"
        id: rename-private-config
        run: mv sidebars.private.js sidebars.js
        working-directory: ./burendo-handbook
        continue-on-error: false

      - name: "Build handbook with content"
        id: build-private-handbook
        run: |
          npm install
          npm run build
        working-directory: ./burendo-handbook
        continue-on-error: false
